{{ if and (eq "aws" .Values.provider) .Values.awsClusterRoleIdentity.create }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSClusterControllerIdentity
metadata:
  name: default
spec:
  {{- if .Values.awsClusterRoleIdentity.allowedNamespaces }}
  allowedNamespaces:
    {{- toYaml .Values.awsClusterRoleIdentity.allowedNamespaces | nindent 4 }}
  {{- else }}
  allowedNamespaces: {} # matches all namespaces
  {{- end }}
{{- end }}