{{ if and (eq "aws" .Values.provider) .Values.cluster.create }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  {{- if .Values.global.namePrefix }}
  name: {{ .Values.global.namePrefix }}{{ .Values.global.name }}
  {{- else }}
  name: {{ .Values.global.name | quote }}
  {{- end }}
  labels:
    {{- with .Values.global.labels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- include "helm-capi-cluster-template.aws-labels" . | nindent 4 }}
spec:
{{- if .Values.cluster.clusterNetwork }}
  clusterNetwork:
    pods:
      cidrBlocks:
        {{- toYaml .Values.cluster.clusterNetwork.pods.cidrBlocks | nindent 8 }}
{{- end }}
  {{- if .Values.cluster.create }}
  controlPlaneRef:
    {{- if eq "aws" .Values.provider }}
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    {{- end }}
    {{- if eq "aws" .Values.provider }}
    kind: AWSManagedControlPlane
    {{- end }}
    {{- if .Values.global.namePrefix }}
    name: {{ .Values.global.namePrefix }}{{ .Values.global.name }}
    {{- else }}
    name: {{ .Values.global.name | quote }}
    {{- end }}
  infrastructureRef:
    {{- if eq "aws" .Values.provider }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    {{- end }}
    {{- if eq "aws" .Values.provider }}
    kind: AWSManagedCluster
    {{- end }}    
    {{- if .Values.global.namePrefix }}
    name: {{ .Values.global.namePrefix }}{{ .Values.global.name }}
    {{- else }}
    name: {{ .Values.global.name | quote }}
    {{- end }}
  {{- end }}
{{ end }}
---
{{- if and (eq "aws" .Values.provider) .Values.cluster.create }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  {{- if .Values.global.namePrefix }}
  name: {{ .Values.global.namePrefix }}{{ .Values.global.name }}
  {{- else }}
  name: {{ .Values.global.name | quote }}
  {{- end }}
  namespace: {{if .Values.global.namespace }}{{ .Values.global.namespace }}{{- else }}default{{- end }}
  labels:
  {{- with .Values.global.labels -}}
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- include "helm-capi-cluster-template.aws-labels" . | nindent 4 }}
{{- end }}
spec: {}
---
{{ if and (and (eq "aws" .Values.provider) .Values.cluster.create) .Values.nodeGroup.create }}
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: EKSConfigTemplate
metadata:
  {{- if .Values.global.namePrefix }}
  name: {{ .Values.global.namePrefix }}{{ .Values.global.name }}
  {{- else }}
  name: {{ .Values.global.name | quote }}
  {{- end }}
  namespace: {{if .Values.global.namespace }}{{ .Values.global.namespace }}{{- else }}default{{- end }}
  labels:
  {{- with .Values.global.labels -}}
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- include "helm-capi-cluster-template.aws-labels" . | nindent 4 }}
spec:
  template: {}
{{- end }}