{{ if and (eq "aws" .Values.provider) .Values.cluster.create }}
apiVersion: {{ .Values.awsControlPlane.apiVersion | default "controlplane.cluster.x-k8s.io/v1beta2" }}
kind: AWSManagedControlPlane
metadata:
  {{- if .Values.global.namePrefix }}
  name: {{ .Values.global.namePrefix }}{{ .Values.global.name }}-control-plane
  {{- else }}
  name: {{ .Values.global.name | quote }}
  {{- end }}
  namespace: {{if .Values.global.namespace }}{{ .Values.global.namespace }}{{- else }}default{{- end }}
  labels:
    {{- with .Values.global.labels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- include "helm-capi-cluster-template.aws-labels" . | nindent 4 }}
spec:
  {{- if .Values.global.namePrefix }}
  eksClusterName: {{ .Values.global.namePrefix }}{{ .Values.global.name }}-cluster
  {{- else }}
  eksClusterName: {{ .Values.global.name | quote }}
  {{- end }}
  identityRef:
    {{- if eq "aws" .Values.provider }}
    kind: AWSClusterRoleIdentity
    {{- if .Values.global.namePrefix }}
    name: {{ .Values.global.namePrefix }}{{ .Values.global.name }}-role-identity"
    {{- else }}
    name: {{ .Values.global.name | quote }}
    {{- end }}
    {{- end }}
    {{- if eq "azure" .Values.provider }}
    kind: AzureClusterIdentity
    {{- end }}
    {{- if eq "gcp" .Values.provider }}
    kind: GCPClusterIdentity
    {{- end }}
  {{- if and (eq "aws" .Values.provider) .Values.awsControlPlane.network }}
  network:
    {{- if .Values.awsControlPlane.network.vpc }}
    vpc:
      id: {{ .Values.awsControlPlane.network.vpc.id }}
    {{- end }}
    {{- if .Values.awsControlPlane.network.subnets }}
    subnets:
    {{- toYaml .Values.awsControlPlane.network.subnets | nindent 4 }}
    {{- end }}
  {{- end }}
  region: {{ .Values.global.region | default "us-east-1" }}
  partition: {{ .Values.awsControlPlane.partition | default "aws" }}
  sshKeyName: {{ .Values.awsControlPlane.sshKeyName | default "default" }}
  version: {{ .Values.global.clusterVersion | default "v1.30.0" }}
  {{- if .Values.awsControlPlane.roleAdditionalPolicies }}
  roleAdditionalPolicies:
    {{- toYaml .Values.awsControlPlane.roleAdditionalPolicies | nindent 4 }}
  {{- end }}
  {{- if .Values.awsControlPlane.logging }}
  logging:
    {{- if .Values.awsControlPlane.logging.apiServer }}
    apiServer: {{ .Values.awsControlPlane.logging.apiServer | default "false" }}
    {{- end }}
    {{- if .Values.awsControlPlane.logging.audit }}
    audit: {{ .Values.awsControlPlane.logging.audit | default "false" }}
    {{- end }}
    {{- if .Values.awsControlPlane.logging.authenticator }}
    authenticator: {{ .Values.awsControlPlane.logging.authenticator | default "false" }}
    {{- end }}
    {{- if .Values.awsControlPlane.logging.controllerManager }}
    controllerManager: {{ .Values.awsControlPlane.logging.controllerManager | default "false" }}
    {{- end }}
    {{- if .Values.awsControlPlane.logging.scheduler }}
    scheduler: {{ .Values.awsControlPlane.logging.scheduler | default "false" }}
    {{- end }}
  {{- end }}
  {{- if .Values.awsControlPlane.additionalTags }}
  additionalTags:
    {{- toYaml .Values.awsControlPlane.additionalTags | nindent 4 }}
  {{- end }}
  {{- if .Values.awsControlPlane.iamAuthenticatorConfig }}
  iamAuthenticatorConfig:
    {{- if .Values.awsControlPlane.iamAuthenticatorConfig.mapRoles }}
    mapRoles:
      {{- toYaml .Values.awsControlPlane.iamAuthenticatorConfig.mapRoles | nindent 6 }}
    {{- end }}
    {{- if .Values.awsControlPlane.iamAuthenticatorConfig.mapUsers }}
    mapUsers:
      {{- toYaml .Values.awsControlPlane.iamAuthenticatorConfig.mapUsers | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.awsControlPlane.endpointAccess }}
  endpointAccess:
    private: {{ .Values.awsControlPlane.endpointAccess.private | default "true" }}
    public: {{ .Values.awsControlPlane.endpointAccess.public | default "false" }}
    {{- if .Values.awsControlPlane.endpointAccess.publicCIDRs }}
    publicCIDRs:
    {{- toYaml .Values.awsControlPlane.endpointAccess.publicCIDRs | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if .Values.awsControlPlane.associateOIDCProvider }}
  associateOIDCProvider: {{ .Values.awsControlPlane.associateOIDCProvider | default "false" }}
  {{- end }}
  {{- if .Values.awsControlPlane.addons }}
  addons:
  {{- toYaml .Values.awsControlPlane.addons | nindent 2 }}
  {{- end }}
{{ end }}
